### ISSUE TITLE
[bug] plugin settings link, does not link properly

### ISSUE THREAD

**Issue by rwkyyy** [dabex/woo-estimate-delivery#4]
From the plugin listing, if you click on the plugin settings, it will open WC settings->general tab.

### WordPress Environment ###

WordPress address (URL): localhost
Site address (URL): localhost
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: ro_RO
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.5
PHP Version: 7.4.1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.6-MariaDB-1:10.4.6+maria~xenial
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Comment by dabex** [comment]
Solved!
